version: '3.7'

services:
  irisdb: 
    image: amirsamary/developing-with-containers:irisdb-version-1.2.0
    hostname: irisdb
    init: true
    container_name: irisdb
    ports:
    - "52773:52773" # 52773 is the webserver/management portal port: http://localhost:52773/csp/sys/UtilHome.csp
    - "51773:51773" # 51773 is the super server
